/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendedorRouteImport } from './routes/vendedor'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as NovaEntregaRouteImport } from './routes/nova-entrega'
import { Route as GastoRouteImport } from './routes/gasto'
import { Route as IndexRouteImport } from './routes/index'

const VendedorRoute = VendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaEntregaRoute = NovaEntregaRouteImport.update({
  id: '/nova-entrega',
  path: '/nova-entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const GastoRoute = GastoRouteImport.update({
  id: '/gasto',
  path: '/gasto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gasto': typeof GastoRoute
  '/nova-entrega': typeof NovaEntregaRoute
  '/pagamento': typeof PagamentoRoute
  '/vendedor': typeof VendedorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gasto': typeof GastoRoute
  '/nova-entrega': typeof NovaEntregaRoute
  '/pagamento': typeof PagamentoRoute
  '/vendedor': typeof VendedorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gasto': typeof GastoRoute
  '/nova-entrega': typeof NovaEntregaRoute
  '/pagamento': typeof PagamentoRoute
  '/vendedor': typeof VendedorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gasto' | '/nova-entrega' | '/pagamento' | '/vendedor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gasto' | '/nova-entrega' | '/pagamento' | '/vendedor'
  id: '__root__' | '/' | '/gasto' | '/nova-entrega' | '/pagamento' | '/vendedor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GastoRoute: typeof GastoRoute
  NovaEntregaRoute: typeof NovaEntregaRoute
  PagamentoRoute: typeof PagamentoRoute
  VendedorRoute: typeof VendedorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendedor': {
      id: '/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof VendedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-entrega': {
      id: '/nova-entrega'
      path: '/nova-entrega'
      fullPath: '/nova-entrega'
      preLoaderRoute: typeof NovaEntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gasto': {
      id: '/gasto'
      path: '/gasto'
      fullPath: '/gasto'
      preLoaderRoute: typeof GastoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GastoRoute: GastoRoute,
  NovaEntregaRoute: NovaEntregaRoute,
  PagamentoRoute: PagamentoRoute,
  VendedorRoute: VendedorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
